config/routes.rb
Rails.application.routes.draw do
mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  mount Spree::Core::Engine, at: '/spree'

  root to: 'home#index'
  resources :products, only: :show
  resources :categories, only: :show
  resources :cart, only: :index, controller: 'cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
module Spree
  module ProductDecorator
    def related_products
      Spree::Product.in_taxons(taxons).where.not(id: id).distinct
    end

    Spree::Product.prepend self
  end
end

app/models/spree/taxon_decorator.rb
module Spree
  module TaxonDecorator
    def get_taxon_breadcrumbs
      self_and_ancestors
        .where('depth > ?', PotepanecConstants::TOP_TAXON_PARENT_DEPTH).order(:depth)
    end

    Spree::Taxon.prepend self
  end
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  self.table_name = 'potepan_suggests'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActiveStorage::SetCurrent

  before_action :set_navigation_categories, only: [:show, :index]
  protect_from_forgery with: :exception

  rescue_from Exception do |e|
    logger.error "Rendering 500 with exception: #{e.message}"
    render template: "errors/500", layout: false, status: :internal_server_error, formats: [:html]
  end

  rescue_from ActionController::RoutingError do |e|
    logger.info "Rendering 404 with exception: #{e.message}"
    render template: "errors/404", layout: false, status: :not_found, formats: [:html]
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    logger.info "Rendering 404 with exception: #{e.message}"
    render template: "errors/404", layout: false, status: :not_found, formats: [:html]
  end

  private

  # メインタクソンの子孫に基づいてナビゲーションメニューを設定(Categoriesに該当するデータが存在する前提で作られているので条件分岐なし)
  def set_navigation_categories
    @categories_taxons = Spree::Taxon.find_by(name: PotepanecConstants::TOP_TAXON_PARENT_NAME).children
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index; end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category_taxon = Spree::Taxon.find(params[:id])
    @top_section_breadcrumbs = @category_taxon.get_taxon_breadcrumbs.to_a
    @products = @category_taxon.all_products
      .includes(master: [:default_price, images: { attachment_attachment: :blob }])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index;end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Spree::Product.includes(master: [:default_price, images: { attachment_attachment: :blob }]).find(params[:id])
    @top_section_breadcrumbs = product_breadcrumbs(@product)
    @related_products = @product.related_products
      .includes(master: [:default_price, images: { attachment_attachment: :blob }])
      .limit(PotepanecConstants::MAX_NUMBER_OF_RELATED_PRODUCTS)
  end

  private

  def product_breadcrumbs(product)
    main_parent_taxon = Spree::Taxon.find_by(name: PotepanecConstants::TOP_TAXON_PARENT_NAME)
    breadcrumbs_taxon = product.taxons.find_by(taxonomy_id: main_parent_taxon.taxonomy_id)
    breadcrumbs = breadcrumbs_taxon.get_taxon_breadcrumbs.to_a
    breadcrumbs << product
    breadcrumbs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end

  def category_to_image_name(category_name)
    mapping = {
      "clothing" => "cloth",
      "caps" => "cap",
      "bags" => "bag",
      "mugs" => "tableware",
    }
    begin
      mapping.fetch(category_name.downcase)
    rescue KeyError
      nil
    end
  end
end

app/views/cart/index.html.erb
<section class="Container CartContainer">
  <h2 class="CartContainer__title">カート</h2>
  <div class="CartWrapper">
    <%= render 'shared/cart/item_list' %>
    <%= render 'shared/cart/order_detail' %>
  </div>
</section>

app/views/categories/show.html.erb
<div class="CategoriesContainer">
  <%= render 'shared/breadcrumbs', breadcrumbs: @top_section_breadcrumbs %>
  <h1 class="CategoriesTitle"><%= t(@category_taxon.name, default: @category_taxon.name) %></h1>
  <section class="CategoryProducts">
    <ul class="CategoryProducts__list">
      <% @products.each do |product| %>
        <li class="CategoryProduct">
          <%= link_to product_path(product.id) do %>
            <%= image_tag(product.images.first.url(:product), :class => "CategoryProduct__image", :alt => product.name) %>
            <p class="CategoryProduct__name">
              <%= product.name %>
            </p>
            <span class="CategoryProduct__price"><%= product.display_price %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>
</div>

app/views/home/index.html.erb
<%= render 'shared/home/first_view' %>
<%= render 'shared/home/category', categories: @categories_taxons %>

app/views/layouts/_footer.html.erb
<div class="Footer">
  <div class="Container Footer__container">
    <div class="Copyright">
      <%= image_tag("common/service-logo.svg", class: "Copyright__logo") %>
      <p class="Copyright__text">Copyright &copy; Potepan Shop <%= Time.current.year %> All rights reserved</p>
    </div>
    <div class="Sns">
      <p class="Sns__title">Follow us on</p>
      <ul class="Sns__list">
        <li class="SnsList__item">
          <%= image_tag("icons/sns/facebook.svg") %>
        </li>
        <li class="SnsList__item">
          <%= image_tag("icons/sns/pinterest.svg") %>
        </li>
        <li class="SnsList__item">
          <%= image_tag("icons/sns/instagram.svg") %>
        </li>
        <li class="SnsList__item">
          <%= image_tag("icons/sns/twitter.svg") %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= favicon_link_tag('favicon.ico') %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;500;700;900&display=swap" rel="stylesheet">

app/views/layouts/_header.html.erb
<div class="Header">
  <nav class="NavigationBar" role="navigation">
    <div class="Container HeaderContainer">
      <div class="NavigationBar__menus">
        <%= link_to root_path do %>
          <%= image_tag("common/service-logo.svg", class: "ServiceLogo") %>
        <% end %>
        <ul class="NavigationMenuList">
          <% taxons.each do |taxon| %>
            <li class="NavigationMenuList__item">
              <%= link_to t(taxon.name, default: taxon.name), category_path(taxon.id), class: "NavigationMenuList__item" %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="NavigationBar__icons">
        <ul class="NavigationIconList">
          <li class="NavigationIconList__item NavigationIconList__item--search">
            <a href="javascript:void(0)" class="NavigationIconWrapper dropdown-toggle" data-toggle="dropdown">
              <%= image_tag("icons/black-color-search.svg", class: "NavigationIconWrapper__icon NavigationIconWrapper__icon--closed") %>
              <span class="NavigationIconWrapper__label">見つける</span>
            </a>
            <div class="NavigationSearchForm">
              <input class="NavigationSearchForm__input dropdown-menu" placeholder="お探しですか？">
              <div class="NavigationSearchForm__icon-wrapper">
                <%= image_tag("icons/white-color-search.svg", class: "NavigationIconWrapper__icon NavigationSearchForm__icon") %>
              </div>
            </div>
          </li>
          <li class="NavigationIconList__item">
            <%= link_to cart_index_path, class: "NavigationIconWrapper" do %>
              <%= image_tag("icons/cart.svg", class: "NavigationIconWrapper__icon") %>
              <span class="NavigationIconWrapper__label">カート</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header', taxons: @categories_taxons %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/products/show.html.erb
<div class="Container ProductsContainer">
  <%= render "shared/breadcrumbs", breadcrumbs: @top_section_breadcrumbs %>
  <div class="ProductWrapper">
    <div class="ProductSlider">
      <div class="ProductSlider__carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @product.images.each_with_index do |image, index| %>
            <div class="item <%= 'active' if index.zero? %>" data-thumb="<%= index %>">
              <%= image_tag(image.url(:product), :class=> "ProductSlider__image", :alt=> @product.name) %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <section class="ProductDetail">
      <h2 class="ProductDetail__name">
        <%= @product.name %>
      </h2>
      <div class="ProductDetail__size-buttons">
        <div class="SizeButton">
          <input id="radio1" class="SizeButton__input" name="size" type="radio" value="S" checked />
          <label for="radio1" class="SizeButton__label">S</label>
        </div>
        <div class="SizeButton">
          <input id="radio2" class="SizeButton__input" name="size" type="radio" value="M" />
          <label for="radio2" class="SizeButton__label">M</label>
        </div>
        <div class="SizeButton">
          <input id="radio3" class="SizeButton__input" name="size" type="radio" value="L" />
          <label for="radio3" class="SizeButton__label">L</label>
        </div>
        <div class="SizeButton">
          <input id="radio4" class="SizeButton__input" name="size" type="radio" value="XL" />
          <label for="radio4" class="SizeButton__label">XL</label>
        </div>
      </div>
      <h3 class="ProductDetail__price">
        <%= @product.display_price %>
      </h3>
      <label class="SubTotalForItem__label" for="item-count">数量</label>
      <div class="SubTotalForItem__select ProductDetail__item-count">
        <select name="item-count" id="item-count">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
        </select>
      </div>
      <a class="ProductDetail__add-button" href="/cart">カートに入れる</a>
    </section>
  </div>
  <section class="RelatedProducts">
    <h3 class="RelatedProducts__title">一緒に見られている商品</h3>
    <ul class="RelatedProducts__list">
      <% @related_products.each do |product| %>
        <li class="RelatedProduct">
          <%= link_to product_path(product.id) do %>
            <%= image_tag(product.images.first.url(:product), :class=> "RelatedProduct__image", :alt => product.name) %>
            <p class="RelatedProduct__name"><%= product.name %></p>
            <span class="RelatedProduct__price"><%= product.display_price %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>
</div>

app/views/shared/_breadcrumbs.html.erb
<ul class="Breadcrumb">
  <li class="Breadcrumb__item">
    <%= link_to t("home"), root_path, class: "Breadcrumb__item Breadcrumb__item--link" %>
  </li>
  <% breadcrumbs.each do |breadcrumb| %>
    <li class="Breadcrumb__item">
      <%# パンくずリストが最後のパンくずリストではない場合は、リンクである必要がある。%>
      <% if breadcrumb.depth != breadcrumbs.last.depth %>
        <%= link_to t(breadcrumb.name, default: breadcrumb.name), category_path(breadcrumb.id), class: "Breadcrumb__item Breadcrumb__item--link" %>
      <% else %>
        <%= t(breadcrumb.name, default: breadcrumb.name) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/cart/_item.html.erb
<li class="ItemInCart">
  <%= image_tag("home/category/cloth.jpg", class: "ItemInCart__image", alt: "服") %>
  <div class="ItemInCart__details">
    <p class="ItemInCart__name">ヒートテックウォームウォームパデットリブブルゾン</p>
    <span>商品番号：00000</span>
    <span>カラー：BLACK</span>
    <span>サイズ：M</span>
    <span>¥ 5,999</span>
    <a href="#" class="ItemInCart__delete-link">削除</a>
  </div>
  <div class="SubTotalForItem">
    <label class="SubTotalForItem__label" for="item-count">数量</label>
    <div class="SubTotalForItem__select">
      <select name="item-count" id="item-count">
        <% (1..10).each do |i| %>
          <option value="<%= i %>"><%= i %></option>
        <% end %>
      </select>
    </div>
    <p class="SubTotalForItem__price">
      <span>小計</span>
      <span>¥ 99,999</span>
    </p>
  </div>
</li>

app/views/shared/cart/_item_list.html.erb
<ul class="ItemListInCart">
  <%= render 'shared/cart/item' %>
  <%= render 'shared/cart/item' %>
  <%= render 'shared/cart/item' %>
</ul>

app/views/shared/cart/_order_detail.html.erb
<div class="OrderDetailsContainer">
  <section class="OrderDetails">
    <h3 class="OrderDetails__title">注文内容</h3>
    <p>
      <span>商品合計</span>
      <span>¥ 9,999</span>
    </p>
    <p>
      <span>送料</span>
      <span>未定</span>
    </p>
    <hr>
    <p class="OrderDetails__total">
      <span>合計</span>
      <span>¥ 99,999</span>
    </p>
    <p>
      <span>内消費税</span>
      <span>¥ 999</span>
    </p>
  </section>
  <button class="OrderButton">購入する</button>
</div>

app/views/shared/home/_category.html.erb
<section class="Category">
  <div class="Container">
    <h2 class="Category__title">CATEGORY</h2>
    <ul class="CategoryList">
      <% categories.each do |category| %>
        <li class="CategoryItem">
          <div class="CategoryItem__image-wrapper">
            <% image_name = category_to_image_name(category.name) %>
            <% if image_name.nil? %>
              <%= image_tag(asset_path("noimage/small.png"), alt: category.name, class: "d-block w-100") %>
            <% else %>
              <%= image_tag(asset_path("home/category/#{image_name}.jpg"), alt: category.name, class: "d-block w-100") %>
            <% end %>
            <div class="CategoryItem__masking">
              <%= link_to "VIEW", category_path(category.id), class: "CategoryItem__button" %>
            </div>
          </div>
          <h3 class="CategoryItem__name"><%= t(category.name, default: category.name) %></h3>
        </li>
      <% end %>
    </ul>
  </div>
</section>

app/views/shared/home/_first_view.html.erb
<section class="FirstView">
  <div class="Container FirstViewContainer">
    <h2 class="FirstView__title">
      Stylish. Elegant.<br>
      Modern.
    </h2>
    <p class="FirstView__description">Everything you need, nothing you don’t.</p>
  </div>
</section>